name: Deploy NiFi Flow via Snowflake

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli

      - name: Setup Snowflake key
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > rsa_key.p8
          chmod 600 rsa_key.p8

      - name: Configure Snowflake connection
        run: |
          snow connection add \
            --connection-name ci_conn \
            --account RBFUEDQ-WBC50273 \
            --user LIRIKSNOWFLAKEADMIN \
            --private-key-path rsa_key.p8 \
            --role MSK_STREAMING_RL \
            --warehouse <YOUR_WAREHOUSE> \
            --database <YOUR_DB> \
            --schema <YOUR_SCHEMA>

      - name: Call Snowflake Procedure
        run: |
          snow sql -c ci_conn -q "CALL AUTO_DEPLOY_NIFI_FLOW();"
